import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { NavBar } from "./_components/navbar";
import Footer from "./_components/footer";

export const metadata: Metadata = {
  title: "Raine Aeternal",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="font-mono bg-[#353535] text-white flex items-center flex-col min-h-screen sm:w-[375px] w-[960px] lg:w-[1024px] mx-auto">
        <NavBar />
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Footer />
      </body>
    </html>
  );
}
